DET_SOURCE_DIR: '/home/liuchong.liu/datasets/AIC21/detection/images/test/S06/'
REID_MODEL: 'reid_model/resnet101_ibn_a_3.pth'
REID_BACKBONE: 'resnet101_ibn_a'
DET_IMG_DIR: '/home/liuchong.liu/datasets/AIC21/detect_merge/'
DATA_DIR: '/home/liuchong.liu/datasets/AIC21/detect_reid3/'
REID_SIZE_TEST: [384, 384]
